animalhouse/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path("api/", include("api.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py

from django.urls import path 
from .views import *

urlpatterns = [
    path("suscrito/<email>", suscrito),
    path("suscribir/<email>", suscribir),
]


app/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User

# Create your models here.

class  Marca(models.Model):
    nombre_marca = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre_marca

class Producto(models.Model):
    codigo = models.CharField(max_length=6, null=True)
    nombre_producto = models.CharField(max_length=50)
    precio = models.IntegerField()
    descripcion = models.TextField()
    nuevo = models.BooleanField()
    marca = models.ForeignKey(Marca, on_delete=models.PROTECT)
    fecha_fabricacion = models.DateField()
    imagen = models.ImageField(upload_to="productos", null=True)
    Stock = models.IntegerField(null=True)

    def __str__(self):
        return self.nombre_producto

opciones_consultas = [
    [0, "consulta"],
    [1, "reclamo"],
    [2, "sugerencia"],
    [3, "felicitaciones"]
]

class Contacto(models.Model):
    nombre = models.CharField(max_length=50)
    correo = models.EmailField()
    tipo_consulta = models.IntegerField(choices=opciones_consultas)
    mensaje = models.TextField()
    avisos = models.BooleanField()

    def __str__(self):
        return self.nombre

class Venta(models.Model):
    id = models.AutoField(primary_key=True)
    fecha = models.DateTimeField(default=datetime.now())
    cliente = models.ForeignKey(to=User, on_delete=models.CASCADE)
    total = models.IntegerField()
    estado = models.CharField(max_length=20, default="EN PREPARACION")
    
    def __str__(self):
        return str(self.id)+" "+str(self.cliente.username)+" "+str(self.fecha)[0:20]

class Detalleventa(models.Model):
    id = models.AutoField(primary_key=True)
    cliente = models.ForeignKey(to=User, on_delete=models.CASCADE, null=True)
    venta = models.ForeignKey(to=Venta, on_delete=models.CASCADE)
    producto = models.ForeignKey(to=Producto, on_delete=models.CASCADE)
    cantidad = models.IntegerField()
    precio = models.IntegerField()

    def __str__(self):
        return str(self.id)+" - "+self.producto.nombre_producto[0:20]+" "+str(self.venta.id)



app/templates/app/producto/agregar.html
{% extends 'app/base.html' %}
{% block contenido %}

{% load crispy_forms_tags %}
        <div class="row">
            <div class="col-12 col-md-6 offset-md-3">

                <div class="card">
                    <div class="card-body">
                            <h2>Nuevo Producto</h2>
                            <hr>
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form | crispy }}
                        <div class="d-flex justify-content-end">
                            <input type="reset" value="Cancelar" class="btn btn-secondary">
                            &nbsp;
                            <input type="submit" value="Guardar" class="btn btn-primary">
                        </div>
                    </form>
                    {{ mensaje }}
            </div>
        </div>
    </div>

</div>

{% endblock %}

app/templates/app/producto/listar.html
{% extends 'app/base.html' %}

{% block js %}
<script>
    function eliminarProducto(id){
        Swal.fire({
            "title":"¿Estas seguro?",
            "text":"esta acción no se puede deshacer",
            "icon":"question",
            "showCancelButton":true,
            "cancelButtonText":"No, Cancelar",
            "confirmButtonText":"Si, Eliminar",
            "reverseButtons":true,
            "confirmButtonColor":"#dc3545"
        })
        .then(function(result){
            if(result.isConfirmed){
                window.location.href = "/eliminar-producto/"+id+"/"
            }
        })
    }
</script>
{% endblock %}

{% block contenido %}
{% load humanize %}
<br>
<br>
<br>
<div class="card">
    <div class="card-body">
        <h2>Listado de productos</h2>
        <hr>
        <table class="table table-striped table-hover table-responsive-sm">
            <tr>
                <th>Codigo</th>
                <th>Nombre</th>
                <th>Precio</th>
                <th>Marca</th>
                <th>¿Es nuevo?</th>
                <th>Stock</th>
                <th>Opciones</th>

            </tr>
        
        {% for p in entity %}
        
            <tr>
                <td>{{ p.codigo }}</td>
                <td>{{ p.nombre_producto | title }}</td>
                <td>{{ p.precio | intcomma }}</td>
                <td>{{ p.marca | title }}</td>
                <td>
                    {% if p.nuevo %}
                    SI
                    {% else %}
                    NO
                    {% endif %}
                </td>
                <td>{{ p.Stock }}</td>
                <td>
                    {% if perms.app.change_producto %}
                    <a href="{%  url 'modificar_producto' p.id %}" class="btn btn-info btn-sm">modificar</a>
                    {% endif %}
                    {% if perms.app.delete_producto %}
                    <a href="#" onclick="eliminarProducto({{ p.id }})" class="btn btn-danger btn-sm">eliminar</a>
                    {% endif %}
                </td>
            </tr>
        
        {% endfor %}
        
        </table>
        <div>
            {% include 'app/paginator.html' %}
        </div>
    </div>
</div>



{% endblock %}

app/templates/app/producto/modificar.html
{% extends 'app/base.html' %}
{% block contenido %}

<br><br>
{% load crispy_forms_tags %}
        <div class="row">
            <div class="col-12 col-md-6 offset-md-3">

                <div class="card">
                    <div class="card-body">
                            <h2>Editar Producto</h2>
                            <hr>
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form | crispy }}
                        <div class="d-flex justify-content-end">
                            <input type="reset" value="Cancelar" class="btn btn-secondary">
                            &nbsp;
                            <input type="submit" value="Editar" class="btn btn-primary">
                        </div>
                    </form>
                    {{ mensaje }}
            </div>
        </div>
    </div>

</div>

{% endblock %}