animalhouse/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path("api/", include("api.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py

from django.urls import path 
from .views import *

urlpatterns = [
    path("suscrito/<email>", suscrito),
    path("suscribir/<email>", suscribir),
]


app/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User

# Create your models here.

class  Marca(models.Model):
    nombre_marca = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre_marca

class Producto(models.Model):
    codigo = models.CharField(max_length=6, null=True)
    nombre_producto = models.CharField(max_length=50)
    precio = models.IntegerField()
    descripcion = models.TextField()
    nuevo = models.BooleanField()
    marca = models.ForeignKey(Marca, on_delete=models.PROTECT)
    fecha_fabricacion = models.DateField()
    imagen = models.ImageField(upload_to="productos", null=True)
    Stock = models.IntegerField(null=True)

    def __str__(self):
        return self.nombre_producto

opciones_consultas = [
    [0, "consulta"],
    [1, "reclamo"],
    [2, "sugerencia"],
    [3, "felicitaciones"]
]

class Contacto(models.Model):
    nombre = models.CharField(max_length=50)
    correo = models.EmailField()
    tipo_consulta = models.IntegerField(choices=opciones_consultas)
    mensaje = models.TextField()
    avisos = models.BooleanField()

    def __str__(self):
        return self.nombre

class Venta(models.Model):
    id = models.AutoField(primary_key=True)
    fecha = models.DateTimeField(default=datetime.now())
    cliente = models.ForeignKey(to=User, on_delete=models.CASCADE)
    total = models.IntegerField()
    estado = models.CharField(max_length=20, default="EN PREPARACION")
    
    def __str__(self):
        return str(self.id)+" "+str(self.cliente.username)+" "+str(self.fecha)[0:20]

class Detalleventa(models.Model):
    id = models.AutoField(primary_key=True)
    cliente = models.ForeignKey(to=User, on_delete=models.CASCADE, null=True)
    venta = models.ForeignKey(to=Venta, on_delete=models.CASCADE)
    producto = models.ForeignKey(to=Producto, on_delete=models.CASCADE)
    cantidad = models.IntegerField()
    precio = models.IntegerField()

    def __str__(self):
        return str(self.id)+" - "+self.producto.nombre_producto[0:20]+" "+str(self.venta.id)



app/templates/app/base.html
{% load static %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>AnimalHouse</title>
	<link rel="icon" href="{% static 'app/img/logo_perro.ico' %}" />
	<link rel="stylesheet" href="{% static 'app/css/styles.css' %}" />
</head>

<body>
	<header>
		<div class="container-hero">
			<div class="container hero">
				<div class="customer-support">
					<i class="fa-solid fa-headset"></i>
					<div class="content-customer-support">
						<span class="text">Servicio al cliente</span>
						<span class="number">+56976459802</span>
					</div>
				</div>

				<div class="container-logo">
					<img src="{% static 'app/img/logo_perro.png' %}" alt="" height="70px">
					<h1 class="logo"><a href="{% url 'home' %}"> AnimalHouse</a></h1>
				</div>

				<div class="container-user">
					<a href="{% url 'perfil' %}"><i class="fa-solid fa-book"></i></a>
						<span class="text">Historial</span>
					<a href="{% url 'carro' %}"><i class="fa-solid fa-basket-shopping"></i></a>
					<div class="content-shopping-cart">
						<span class="text">Carrito</span>
						<span class="number"></span>
					</div>
				</div>
			</div>
		</div>

		<div class="container-navbar">
			<nav class="navbar container">
				<i class="fa-solid fa-bars"></i>
				<ul class="menu">
					<li><a href="{% url 'home' %}">Inicio</a></li>
					<li><a href="{% url 'productos' %}">Productos</a></li>
					<li><a href="{% url 'somos' %}">Quienes somos</a></li>
					<li><a href="{% url 'contacto' %}">Contacto</a></li>
					{% if perms.app.add_producto %}
					<li><a href="{% url 'agregar_producto' %}">Agregar productos</a></li>
					{% endif %}
					{% if perms.app.view_producto %}
					<li><a href="{% url 'listar_productos' %}">Listado productos</a></li>
					{% endif %}
					{% if user.is_authenticated %}
					<li><a href="{% url 'logout' %}">Cerrar sesion</a></li>
					<li><a href="#">{{ user.username}}</a></li>
					{% if suscrito %}
                    👌
					{% else %}
                    🤦‍♂️
					{% endif %}
					{% else %}
					<li><a href="{% url 'login' %}">Iniciar sesión</a></li>
					<li><a href="{% url 'registro' %}">Registrate</a></li>
					{% endif %}
				</ul>

				<form class="search-form">
					<input type="search" placeholder="Buscar..." />
					<button class="btn-search">
						<i class="fa-solid fa-magnifying-glass"></i>
					</button>
				</form>
			</nav>
		</div>
	</header>
	<!--slider-->
	<main class="main-content">



        {% block contenido %}
        {% endblock %}

	</main>
	<!-- footer -->
	<footer class="footer">
		<div class="container container-footer">
			<div class="menu-footer">
				<div class="contact-info">
					<p class="title-footer">Información de Contacto</p>
					<ul>
						<li>
							Casa Matriz
							<p>Calle N°2867 </p>
							<p>Melipilla,75074, Chile</p>
						</li>
						<li>Teléfono: +56976459802 </li>
						<li>Whatsapp: +56976459802</li>
						<li>EmaiL: AnimalHouse@gmail.cl</li>
					</ul>
					<div class="social-icons">
						<span class="facebook">
							<i class="fa-brands fa-facebook-f"></i>
						</span>
						<span class="twitter">
							<i class="fa-brands fa-twitter"></i>
						</span>
						<span class="youtube">
							<i class="fa-brands fa-youtube"></i>
						</span>
						<span class="pinterest">
							<i class="fa-brands fa-pinterest-p"></i>
						</span>
						<span class="instagram">
							<i class="fa-brands fa-instagram"></i>
						</span>
					</div>
				</div>

				<div class="information">
					<p class="title-footer">Información</p>
					<ul>
						<li><a href="#">Acerca de Nosotros</a></li>
						<li><a href="#">Información Delivery</a></li>
						<li><a href="#">Politicas de Privacidad</a></li>
						<li><a href="#">Términos y condiciones</a></li>
						<li><a href="#">Contactános</a></li>
					</ul>
				</div>

				<div class="my-account">
					<p class="title-footer">Mi cuenta</p>

					<ul>
						<li><a href="#">Mi cuenta</a></li>
						<li><a href="#">Historial de compras</a></li>
						<li><a href="#">Donde vienen mis compras</a></li>

					</ul>
				</div>

				<div class="newsletter">
					<p class="title-footer">Registrate</p>

					<div class="content">
						<p>
							Suscribete y obten un 5% de descuento en compras
						</p>
						<br>
						<a href="{% url 'suscribir' %}">Suscribete</a>
					</div>
				</div>
			</div>

			<div class="copyright">
				<p>
					Copyright © 2023 - All Rights Reserved
				</p>

				<img src="{% static 'app/img/payment.png' %}" alt="Pagos">
			</div>
		</div>
	</footer>

	<script src="https://kit.fontawesome.com/81581fb069.js" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

	{% if messages %}
			{% for m in messages %}
				<script>
					Swal.fire({
						"title": "Felicitaciones",
						"text": "{{m}}",
						"icon":"success"
					})
				</script>
			{% endfor %}
		{% endif %}

</body>

</html>

app/templates/app/carro.html
{% extends 'app/base.html' %}


{% load static %}

{% block contenido %}
<div class="card">
    <div class="card-body">
<h1 class="heading-pag"><span>Carrito de compras</span></h1> 
<section class="contenedor">
    <table class="table table-striped table-hover table-responsive-sm">
      <thead>
        <tr>
          <th>Codigo</th>
          <th>Detalle</th>
          <th>Precio</th>
          <th>Cantidad</th>
          <th>Subtotal</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for item in carro %} 
            <tr>
              <td>{{ item.0 }}</td>
              <td>{{ item.1 }}</td>
              <td>{{ item.2 }}</td>
              <td>{{ item.3 }}</td>
              <td>{{ item.4 }}</td>
              <td>
                <a href="{% url 'dropitem' item.0 %}">
                  <img  class="img-quitar" src="{% static 'img/inicio/quitar-del-carrito.png'%}" alt="">
                </a>
              </td>
            </tr>
        {% endfor %}
      </tbody>
    </table>
</section>

{% if not carro %}
<h2 class="vacio-carrito">Tu carrito esta vacio!.</h2>
{% else %}
<div class="comprar">
  <a href="{% url 'comprar' %}" class="btn btn-info btn-sm">Comprar</a>
</div>
</div>
</div>
{% endif %}
{% endblock %}

app/templates/app/contacto.html
{% extends 'app/base.html' %}
{ % load static % }


{% block contenido %}
{% load crispy_forms_tags %}

<br>
<br>
<div class="row">
    <div class="col-12 col-md-6 offset-md-3">
        <div class="card">
            <div class="card-body">

        <h2>Contactanos!</h2>
        <hr>
        <form action="" class="" method="post">

            {% csrf_token %}

            {{ form  | crispy }}

            <!-- <label for="nombre">Nombre</label>
            <input type="text" id="nombre" name="nombre">
            <br>
            <label for="email">Email</label>
            <input type="email" id="email" name="email" placeholder="tu@email.cl">
            <br>
            <label for="telefono">Telefono</label>
            <input type="number" name="telefono" id="telefono">
            <br>
            <label for="tipoconsulta">Tipo consulta</label>
            <select name="tipoconsulta" id="tipoconsulta">
                <option value="">seleccionar</option>
                <option value="consulta">consulta</option>
                <option value="reclamo">reclamo</option>
                <option value="sugerencia">sugerencia</option>
                <option value="felicitaciones">felicitaciones</option>
            </select>
            <br>
            <label for="mensaje">Mensaje</label>
            <textarea name="mensaje" id="mensaje" cols="30" rows="10"></textarea> -->
            <!-- <br>
            <input type="checkbox" name="avisos" id="avisos" checked>
            <label for="avisos">¿Desea recibir promociones/avisos a su email?</label> -->
            <hr>
            <br>
            <div class="d-flex justify-content-end">
            <input type="reset" value="Cancelar" class="btn btn-secondary">
            &nbsp;
            <button type="submit" id="btnEnviar" class="btn btn-primary">Enviar</button>
            </div>

        </form>

        {{ mensaje }}

        </div>
        </div>
    </div>
</div>
       
       

        <table id="tablacontactos">
            
        </table>

{% endblock %}

app/templates/app/home.html
{% extends 'app/base.html' %}
{% load static %}

{% block css %}

<link rel="stylesheet" href="styles.css" />

{% endblock %}

{% block js %}

<script src="https://kit.fontawesome.com/81581fb069.js" crossorigin="anonymous"></script>

{% endblock %}

{% block contenido%}

{% load humanize %}
	<!--slider-->
	<section>
		<div class="slider">
			<ul>
				<li><img src="{% static 'app/img/slider2-2.jpg' %}"></li>
				<li><img src="{% static 'app/img/slider2-3.jpg' %}"></li>
				<li><img src="{% static 'app/img/slider2-4.jpg' %}"></li>
				<li><img src="{% static 'app/img/slider2-5.webp' %}"></li>
				<li><img src="{% static 'app/img/slider2.jpg' %}"></li>
			</ul>
		</div>
	</section>
	<!--slider-->
	<main class="main-content">
		<section class="container container-features">
			<div class="card-feature">
				<i class="fa-solid fa-plane-up"></i>
				<div class="feature-content">
					<span>Envío gratuito </span>
					<p>En pedido superior a $1500</p>
				</div>
			</div>
			<div class="card-feature">
				<i class="fa-solid fa-wallet"></i>
				<div class="feature-content">
					<span>Reembolso</span>
					<p>100% garantía de devolución de dinero</p>
				</div>
			</div>
			<div class="card-feature">
				<i class="fa-solid fa-gift"></i>
				<div class="feature-content">
					<span>Tarjeta regalo especial</span>
					<p>Ofrece bonos especiales con regalo</p>
				</div>
			</div>
			<div class="card-feature">
				<i class="fa-solid fa-headset"></i>
				<div class="feature-content">
					<span>Servicio al cliente 24/7</span>
					<p>LLámenos 24/7 al +56976459802</p>
				</div>
			</div>
		</section>


		<h1 class="heading-1">Mejores Productos</h1>
		<section class="container top-products">
			

			<!-- <div class="container-options">
				<span class="active">Destacados</span>
				<span>Más recientes</span>
				<span>Mejores Vendidos</span>
			</div> -->

            
			<main class="main-content"></main>

                {% for p in productos %}
				
				<!-- Producto 5 -->
				<div class="card-product">
					<div class="container-img">
                        {% if p.imagen %}
						<img src="{{ p.imagen.url }}" alt="imagen producto" />
						{% endif %}
                        <h5>{{p.marca | capfirst}}</h5>
                        <div class="button-group">
							<span>
								<i class="fa-regular fa-eye"></i>
							</span>
							<span>
								<i class="fa-regular fa-heart"></i>
							</span>
							<span>
								<i class="fa-solid fa-code-compare"></i>
							</span>
						</div>
					</div>
					<div class="content-card-product">
						<div class="stars">
							<i class="fa-solid fa-star"></i>
							<i class="fa-solid fa-star"></i>
							<i class="fa-solid fa-star"></i>
							<i class="fa-solid fa-star"></i>
							<i class="fa-regular fa-star"></i>
						</div>
						<h3>{{ p.nombre_producto | title}} </h3>
						<a href="{% url 'addtocar' p.codigo %}" class="add-cart" data-id="1"><i class="fa-solid fa-basket-shopping">Agregar al carro</i></a>
						<p class="price">${{ p.precio | intcomma }}</p>
						<span class="stock">Quedan {{ p.Stock }} unidades</span>
					</div>
				</div>
                {% endfor %}
			</div>
		</section>

		<section class="container top-categories">
			<h1 class="heading-1">Categorías</h1>
			<div class="container-categories">
				<div class="card-category category-x1">
					<p>Alimentos</p>
					<span>Ver más</span>
				</div>
				<div class="card-category category-x2">
					<p>Juguetes</p>
					<span>Ver más</span>
				</div>
				<div class="card-category category-x3">
					<p>Outlet</p>
					<span>Ver más</span>
				</div>
			</div>
		</section>


		<section class="container specials">
			<h1 class="heading-1">Especiales</h1>

			<div class="container-products">
				
				
			</div>
		</section>

		<section class="container blogs">
			<h1 class="heading-1">Últimos Blogs</h1>

			<div class="container-blogs">
				<div class="card-blog">
					<div class="container-img">
						<img src="{% static 'app/img/perro_mojado.jpg' %}" alt="Imagen Blog 1" />
						<div class="button-group-blog">
							<span>
								<i class="fa-solid fa-magnifying-glass"></i>
							</span>
							<span>
								<i class="fa-solid fa-link"></i>
							</span>
						</div>
					</div>
					<div class="content-blog">
						<h3>Descubre cómo refrescar a un perro en verano</h3>
						<span>29 Noviembre 2022</span>
						<p>
							Descubre los consejos para refrescar a un perro en verano y los productos que le ayudarán a
							sobrellevar las altas temperaturas.
						</p>
						<a href="{% url 'noticia_uno' %}" class="btn-read-more">Leer más</a>
					</div>
				</div>
				<div class="card-blog">
					<div class="container-img">
						<img src="{% static 'app/img/gato_maleta.jpg' %}" alt="Imagen Blog 2" />
						<div class="button-group-blog">
							<span>
								<i class="fa-solid fa-magnifying-glass"></i>
							</span>
							<span>
								<i class="fa-solid fa-link"></i>
							</span>
						</div>
					</div>
					<div class="content-blog">
						<h3>Los mejores transportines para gatos</h3>
						<span>20 Enero 2023</span>
						<p>
							En AnimalHouse te dejamos esta guía para que elijas el mejor transportín para tu gato
							atendiendo a vuestras necesidades y planes de vacaciones para que no vuelvas a viajar sin la
							compañía de tu peludo.
						</p>
						<a  href="{% url 'noticia_dos' %}" class="btn-read-more">Leer más</a>
					</div>
				</div>
				<div class="card-blog">
					<div class="container-img">
						<img src="{% static 'app/img/adiestramiento.jpg' %}" alt="Imagen Blog 3" />
						<div class="button-group-blog">
							<span>
								<i class="fa-solid fa-magnifying-glass"></i>
							</span>
							<span>
								<i class="fa-solid fa-link"></i>
							</span>
						</div>
					</div>
					<div class="content-blog">
						<h3>Adiestramiento canino en Chile</h3>
						<span>11 Mayo 2023</span>
						<p>
							La educación es una parte esencial del cuidado de nuestras mascotas, encuentra aquí los
							mejores adiestradores caninos en Chile.
						</p>
						<a href="{% url 'noticia_tres' %}" class="btn-read-more">Leer más</a>
					</div>
				</div>
			</div>
		</section>
	</main>
	
{% endblock %}

app/templates/app/noticia_dos.html
{% extends 'app/base.html' %}
{% load static %}


{% block css %}
{% endblock %}

{% block js %}


{% endblock %}


{% block contenido%}


{% load humanize %}
<div>
    <img src="{% static 'app/img/perro_mojado.jpg' %}" alt="">
</div>


<h1>Descubre cómo refrescar a un perro en verano</h1>


<p>Nuestros amigos peludos, especialmente los perros, sufren más que nosotros las altas temperaturas, ya que su sistema de refrigeración es diferente al nuestro. Al no tener glándulas sudoríparas por todo el cuerpo, los perros no pueden regular su temperatura como los humanos y lo hacen a través del sudor en las almohadillas de las patas y el jadeo. </p>


<h2>4 consejos para refrescar a tu perro en verano y ¡disfrutarlo!</h2>


<p>Los perros también pueden sufrir el temido golpe de calor, por lo que es primordial mantener la temperatura corporal de nuestro perro. Aquí te dejamos algunos consejos para combatir las altas temperaturas y mantener a tu amigo peludo fresco:</p>
<h3>Mantén su agua limpia y fresca</h3>
<p>Aconsejamos tener un bebedero de refuerzo durante el periodo estival y cambiar el agua con frecuencia. Esto es indispensable para mantener a tu perro hidratado.</p>


<h3>Refresca a tu perro con agua</h3>


<p>Pasa un paño húmedo o una toalla húmeda sobre el pelo de tu perro para refrescarle y ayudarle a combatir las altas temperaturas.</p>


<h3>Ten cuidado con el corte de pelo</h3>


<p>Aunque parezca mentira, no es recomendable cortar mucho el pelo en la mayoría de los perros, puesto que el pelo aparte de aportar protección frente a lesiones o quemaduras, les ayuda a combatir el calor. Es mucho más recomendable cepillar regularmente a nuestros perros para eliminar el pelo muerto y evitar los nudos.</p>


<h2>Bebedero congelable</h2>


<p>El comedero refrescante Summer Vibes es muy fácil de utilizar solo tienes que retirar el bowl del soporte y meterlo al congelador durante 2 horas aproximadamente. Cuando lo saques, lo vuelvas a colocar y lo rellenes de agua, ésta se mantendrá fría para que tu perro o gato pueda disfrutar de agua fresquita para calmar la sed y el calor.</p>


<h2>Camas y mantas refrescantes para perros</h2>


<p>Un descanso sin alteraciones por el calor es ideal para estar bien despejado y con energía al día siguiente. Te indicamos las mejores camas para refrescar a tu perro en verano:


    Esterilla para perros refrigerante color gris: Esterilla refrigerante para perros que proporciona un efecto refrescante al contacto corporal y se mantiene fría durante varias horas. Tras un breve descanso se podrá utilizar de nuevo, ya que funciona sin refrigeración ni electricidad.
    Cojín refrescante para mascotas Summer Vibes: Cojín refrescante ideal para el descanso de las mascotas que reduce su sensación térmica corporal. Funciona sin baterías ni cables.
    Pet esterilla refrigerante azul para perros: Esterilla refrigerante para perros rellena de goma espuma y gel no tóxico. En condiciones normales, la esterilla refrigerante tendrá una temperatura 5-10 ℃ menor que la temperatura de la estancia.</p>


{% endblock %}

app/templates/app/noticia_tres.html
{% extends 'app/base.html' %}
{% load static %}


{% block css %}
{% endblock %}

{% block js %}


{% endblock %}


{% block contenido%}


{% load humanize %}
<div>
    <img src="{% static 'app/img/adistramiento.jpg' %}" alt="">
</div>


<h1>Adiestramiento Canino </h1>


<p>Los fundamentos del aprendizaje se basan, según los expertos, en cómo la orientación de las emociones condicionan los procesos mentales. De ahí también parte el adiestramiento canino, donde intervienen factores decisivos como la motivación y la concentración del animal para que interiorice todas aquellas lecciones que se le tratan de enseñar.


    Los adiestradores de perros también hablan de entrenamiento cuando ponen en práctica la disciplina de educación canina, proceso donde entran en juego los sentidos del animal, su carácter y sus necesidades. 
    
    Para ello, los educadores caninos y los perros tienen que establecer una comunicación que nazca de la confianza. Solo así, y con paciencia, se puede conseguir el objetivo de redirigir la conducta del animal para que resulte beneficiosa tanto para él como para su entorno.
    
    De ahí que los dueños de perros recurran al adiestramiento canino con el fin de tener a un compañero equilibrado de su lado que, además, explota todo su potencial en lo relativo a sus capacidades gracias a la labor del adiestrador de perros.
    
    Comprendiendo todo lo anterior, pasemos a situarnos en una capital como Madrid, donde el inmenso tráfico de gente y un acelerado estilo de vida marcan el ritmo de esta ciudad. Y ante tantos estímulos, un perro es capaz de desarrollar comportamientos indeseados que se alimentan de emociones como el miedo o el estrés que limitan su interacción con el entorno y, sobre todo, empobrecen su calidad de vida.
    
    De esta forma, el perro en cuestión puede evitar relacionarse con otros perros o incluso enfrentarse a ellos, sino lo hace contra personas e incluso vehículos. También puede llegar a no controlar el momento ni el lugar donde hace sus necesidades, o bien dar rienda suelta a comportamientos destructivos en casa, entre otros problemas.
    
    Sea cual sea el caso, el adiestramiento canino en Madrid se convierte en un recurso útil para corregir determinadas asociaciones que el perro no hace de la forma adecuada. Y una vez que su comportamiento se vuelve equilibrado, el perro consigue disfrutar saludablemente del tiempo que pasa en casa, de sus paseos al exterior y de conocer tanto a perros como a personas desconocidas. </p>


    <h2>¿Cuál es el precio de un adiestrador de perros ?</h2>


    <p>Cabe destacar que el precio que cobra un adiestrador varía en función del servicio que presta. Es decir, que no cuesta lo mismo un proceso de obediencia básica, como hacer que el perro se quede sentado, que resolver un problema de conducta, el cual lleva más tiempo de corregir. 


        La raza, la edad y el carácter del perro condicionan este precio ya que condiciona el tiempo que hay que dedicarle al adiestramiento canino. Hasta el domicilio es un factor a tener en cuenta, ya que muchos educadores caninos se desplazan hasta tu propia casa para trabajar con el perro in situ.
        
        De forma habitual, una sesión de adiestramiento canino en Madrid de 1 hora de duración puede llegar a rondar entre los 20 y los 50 euros. En caso de que el animal sea receptivo con el adiestramiento, el servicio se completaría en varias sesiones. En otros casos, la cuota es mensual según la oferta que haga cada adiestrador particular o el centro de educación canina al que acudas.</p>




{% endblock %}

app/templates/app/noticia_uno.html
{% extends 'app/base.html' %}
{% load static %}


{% block css %}
{% endblock %}

{% block js %}


{% endblock %}


{% block contenido%}


{% load humanize %}
<div>
    <img src="{% static 'app/img/gato_maleta.jpg' %}" alt="">
</div>
 <h1>Los mejores transportines para gatos</h1>


<p>El transportín es un elemento esencial si tu mascota es un gato o un perro pequeño. Si te gusta viajar, sueles llevar a tu gato contigo habitualmente o prefieres llevarlo al veterinario de forma segura los transportines para gatos son un accesorio imprescindible para ti. 


    De plástico duro, en forma de caja, desmontable, mullido, con ruedas o en forma de mochila, hay transportines para todos los gustos y preferencias, tanto para las del animal como las del dueño. Si te ves abrumado con todas las opciones disponibles, desde Tiendanimal te lo ponemos fácil para que elijas el mejor transportín para tu gato. ¡Sigue leyendo para enterarte de cuáles son los mejores transportines para gatos!</p>


<h2>¿Cómo elegir el mejor transportín para tu gato?</h2>


<p>En función de la asiduidad con la que viajes, el tamaño de tu animal y tus preferencias personales en cuanto a comodidad de transporte deberás elegir un modelo de transportín por encima de otros.


    Lo primero que hay que tener en cuenta es que el transportín se adapte al tamaño de nuestro animal, que le permita moverse y dar vueltas con facilidad, sin sentirse agobiado en ningún momento. 
    
    Otra cuestión a tener en cuenta a la hora de elegir un transportín u otro es la forma elegida para trasladarse con el animal, es decir, si se va caminando, en coche, en tren o en otro tipo de vehículo, así como la preferencia personal del dueño de llevar a su mascota, si prefiere cargarlo de un hombro, de ambos, en maleta, etc.
    
    No te pierdas nuestro artículo “Cómo viajar con tu gato en coche“</p>


    <h2>Consejos para elegir el mejor transportín para gatos</h2>


    <p>El mejor transportín para tu gato será el que se adapte mejor a sus necesidades y a las tuyas y el que os resulte más cómodo a los dos. Si viajas muy frecuentemente, el animal pasará muchas horas dentro del transportín, así que lo mejor es hacerse con uno que sea fácil de manejar para ti y lo más agradable posible para él. 


        Si viajas además en avión tendrás que informarte de las normas de cada aerolínea para saber qué tipo de transportín necesita tu mascota y en qué condiciones puede viajar, además de todo lo que necesitas para no tener problemas ni en el aeropuerto ni en el país de destino. 
        
        La mejor manera de saber el tamaño del transportín es midiendo a tu animal desde diferentes partes:
        
        Desde el hocico hasta el inicio de la cola.
        Las patas delanteras desde el suelo hasta la articulación superior.
        El ancho de los hombros.
        Desde el suelo hasta la parte más alta de la cabeza o las orejas si las tiene hacia arriba.
        Teniendo ya estas cifras, debemos pasar a elegir el tamaño del transportín realizando una serie de cuentas:
        
        Ancho: El ancho de sus hombros multiplicado por 2.
        Largo: El largo total del animal más la mitad del total de sus patas.
        Alto: La altura del animal más 2 centímetros.</p>


        


{% endblock %}